### ISSUE TITLE
doesn't work on linux

### ISSUE THREAD

**Issue by jabuxas** [RoseTheFlower/MetroSteam#14]
![image](https://user-images.githubusercontent.com/94939040/215100343-f393a063-3216-4718-bfe0-3589b2e6f3c2.png)
appending the css code to webkit.css makes the bar from the store white, and nothing else changes apparently. even in game.

**Comment by RoseTheFlower** [comment]
I'm not sure. I don't have Linux installed and the instructions are based on what used to work for people. It's probably best to ask the other users on the [Metro Discord](https://discord.gg/YfSmpxYF), which I did, but there is no response as of yet.

**Comment by jabuxas** [comment]
to keep in note, i applied the patch before appending the css, but i did try before applying the patch and still didnt work

**Comment by jabuxas** [comment]
https://github.com/Jonius7/SteamUI-OldGlory/wiki/Linux is this any useful?

**Comment by RoseTheFlower** [comment]
How is it as of late?

**Comment by headassbtw** [comment]
This got fixed a while back, through either SFP or the fateful client update

Works On My Machine:tm:

![Screenshot_20231008_112057](https://github.com/RoseTheFlower/MetroSteam/assets/16214950/70af263b-0e10-4880-beb7-313ba1a54867)

**Comment by jabuxas** [comment]
truly has been working. forgot to close it.
