### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Fan4eGGG** [RoseTheFlower/MetroSteam#15]
ive got this error. whats wrong? using selfcontained

![image](https://github.com/RoseTheFlower/MetroSteam/assets/40491634/d0b5b469-fdc5-4def-861c-f5d30fb77418)

**Comment by PhantomGamers** [comment]
Seems like you have some other service running on port 8080 on your PC

You can run this in command prompt to see what service that is:
```
for /f "tokens=5" %a in ('netstat -aon ^| findstr ":8080" ^| findstr "LISTENING"') do @for /f "tokens=1" %b in ('tasklist /fi "pid eq %a"') do @echo %b
```

**Comment by Fan4eGGG** [comment]
How do I know what Im running on port 8080?
I disabling this port with this command?

**Comment by RoseTheFlower** [comment]
I'll close, as this is related to SFP developed by @PhantomGamers rather than to my skin, and so it's not something I can help with. You can still discuss here or raise the issue there.

**Comment by Fan4eGGG** [comment]
> You can run this in command prompt

после ввода ничего не происходит.
