### ISSUE TITLE
Library Shelf Issue

### ISSUE THREAD

**Issue by Sekenx** [RoseTheFlower/MetroSteam#17]
When clicking on a shelf drop-down, example is attached, you cannot click any of the steam space, you're forced to select and option.

For example, if I click on "Sort by" I need to select a category, I can't just click off the menu and continue using steam, it gets soft-locked.

In the attached image, the blue area can only be clicked on but the red areas can't as examples, but can be in normal steam ui.

Tested on the normal steam ui and you can click anywhere outside the menu and it disappears.

![Capture](https://github.com/RoseTheFlower/MetroSteam/assets/6661770/cced6f81-2ace-43d7-804d-3c69573eefb8)

**Comment by RoseTheFlower** [comment]
This is caused by my global `transition`-related overrides. Setting them to 0 would solve this but break other things. I'll have to find the transition property of the class responsible for this dropdown and reintroduce it.

**Comment by RoseTheFlower** [comment]
I set the global transition duration and delay to 0 again but solved the download items softlock by reintroducing its original duration. This addresses the dropdown issue but please be on the lookout for other issues and let me know if you see any.
