### ISSUE TITLE
Millenium - Drop Down Skinless

### ISSUE THREAD

**Issue by Sekenx** [RoseTheFlower/MetroSteam#19]
May not be a skin issue as it works with SFP no problem, but the menu dropdowns aren't skinned when running through Millennium, I downloaded it to see how it compared to SFP, ended up going back to SFP because of this - I ensured that JS injection was enabled but still the same issue there too - could you take a look? 

Store, Library, Community etc. drop-down menus. 

Thanks :D

**Comment by RoseTheFlower** [comment]
Hey, I don't use JS and it definitely looks like an issue of Millennium. I haven't experienced the issue when using SFP and I'm not experiencing it now when using CSS Loader. It's best to ask the creator of the patcher.

![image](https://github.com/RoseTheFlower/MetroSteam/assets/4759227/2947f484-c904-4b38-81fb-8a754c5347f9)

**Comment by Sekenx** [comment]
Alright thanks!
