### ISSUE TITLE
Background is dimming

### ISSUE THREAD

**Issue by Fan4eGGG** [RoseTheFlower/MetroSteam#23]
I noticed that with the Metro theme enabled, the background in the library looks "faded" as if a translucent black filter had been applied to it. like [this](https://prnt.sc/AReLQ5aIPVRX) or [that](https://prnt.sc/nuwFiR7JogoR)
how can I fix this?

**Comment by RoseTheFlower** [comment]
That's intentional, to better match the original Metro where game screenshots were the background and then a semi-transparent layer was laid over. You can control the opacity via --gameimageopacity.

**Comment by Fan4eGGG** [comment]
> --gameimageopacity

where can i find it?

**Comment by RoseTheFlower** [comment]
Add it to custom.css between the html:root brackets, like `--gameimageopacity:0.99;`

**Comment by Fan4eGGG** [comment]
like this? if yes it didnt help :(
![image](https://github.com/RoseTheFlower/MetroSteam/assets/40491634/bcc45a9c-2ac4-4aa4-9a17-d27347f294d3)

**Comment by RoseTheFlower** [comment]
That looks like libraryroot.custom.css, not [custom.css](https://github.com/RoseTheFlower/MetroSteam/blob/master/custom.css).

**Comment by Fan4eGGG** [comment]
no, this is cutom
![image](https://github.com/RoseTheFlower/MetroSteam/assets/40491634/301beb6d-22e3-478b-ad92-c0ac5176701a)

Am I doing something wrong?

**Comment by RoseTheFlower** [comment]
You'd have to have the following as your content of custom.css unless you want any other tweaks.

```
html:root
{
--gameimageopacity: 1;
}
```

The file would be in the same folder as the rest if you use SFP or you'd have to modify the variable directly via libraryroot if you use CSSLoader. With CSSLoader, it would get overridden by an update though.

**Comment by Fan4eGGG** [comment]
oh. so i missed a `html:` before `root` now i see. why didn't you tell me that.
It works fine now, thank you.
