### ISSUE TITLE
Beta Update breakage

### ISSUE THREAD

**Issue by Zacam** [RoseTheFlower/MetroSteam#29]
Not sure if this is more an SFP Issue with Hooking anything, but covering bases since I use this theme, as a heads up:

March 8th Beta Client update has this note to it:
- Modified CSS classnames to reduce package size and reduce feature leaks

Since that update, SFP still runs as normal, but no theme elements (outside of this theme's Chat Window modifications) are applying.

The fact that Friends List/Chat is still working is throwing me as to whether or not this is a Theme problem, or SFP one.

**Comment by PhantomGamers** [comment]
This is *technically* a skin issue. SFP is still injecting fine, but because the class names were changed and the skin still targets the old class names it no longer has any effect on the client.

With that said, I plan to introduce a feature in SFP to fix this for older skins, but it *probably* won't happen until the update hits stable, so for now I would suggest just swapping back to stable.

**Comment by RoseTheFlower** [comment]
It is entirely Valve's fault and it affects every skin, as discussed on [reddit](https://www.reddit.com/r/Steam/comments/1ba101m/valve_may_potentially_kill_theme_customization_in/) and [Steam](https://steamcommunity.com/groups/SteamClientBeta/discussions/3/4298194722189670859/).

I don't think it's possible on my end to support both the stable and the beta, as the classes are completely different. I'm waiting for the beta to become live to ensure there are no changes to the "encrypted" classes before I convert. From there, the reliability of the skin will depend heavily on Valve not randomizing their class names again. If they do it frequently, someone will have to track all the changes and timely convert again, which may become a chore.

**Comment by Zacam** [comment]
Wow. Wasn't expecting feedback so quickly. Thank you, both.
I figured that would be the case, sorry if it was unnecessary to open an issue, but at least there is something here to point to or be seen by anybody else with the same.

I'll look forward to these changes hitting "Stable".

**Comment by RoseTheFlower** [comment]
The latest version of CSSLoader has a checkbox to support the current beta client. I see no way to enable the beta on my end, so I haven't tested it myself.

**Comment by RoseTheFlower** [comment]
[My test branch](https://github.com/RoseTheFlower/MetroSteam/tree/test) now contains the converted classes. Works very well on the beta so far, with a few exceptions that will need to be updated by hand later.

**Comment by Zacam** [comment]
Oh, very nice! I pulled a copy of that into my Skins folder as ""MetroSteam-Beta".
So far, all is working perfectly.

That class obfuscation though, holy crud.

**Comment by RoseTheFlower** [comment]
Closing now that the beta is stable and there were two reports by people having no issues after the class conversion.
