### ISSUE TITLE
Hiding VAC status

### ISSUE THREAD

**Issue by Fan4eGGG** [RoseTheFlower/MetroSteam#30]
sup.
if I put the code in the browser - it works:
```
.profile_ban_status {
  display: none;
  visibility: hidden;
}
```
But if I add the same thing to **_custom.css_**, nothing happens. But it worked literally a month or two ago. am I doing something wrong? please clarify.
thanks.

**Comment by PhantomGamers** [comment]
If you're trying to do this for the profile page then it needs to be added to the webkit.css file

**Comment by RoseTheFlower** [comment]
Phantom's suggestion should work. You don't need to set visibility to hidden, by the way. The element gets completely removed with the `display: none` override.

**Comment by Fan4eGGG** [comment]
>  it needs to be added to the webkit.css

thats worked. I always thought that any custom code should be added to **custom.css**.
thanks for the help.

> The element gets completely removed with the `display: none` override. 

u r right, thank u!

**Comment by RoseTheFlower** [comment]
>I always thought that any custom code should be added to custom.css.

That's ideal, as it would prevent any overriding from updating the skin. webkit.css is currently an exception, as it doesn't import custom.css.
