### ISSUE TITLE
Hide news section

### ISSUE THREAD

**Issue by linguaccia22** [RoseTheFlower/MetroSteam#36]
Hi, I just installed this theme that I really like, I just wanted to ask, is it possible to disable or hide the news section? so as to have an even cleaner games page.

Thank you

**Comment by RoseTheFlower** [comment]
Hi, do you mean the What's New part? See https://github.com/RoseTheFlower/MetroSteam/blob/fdababe9eacadaea008ce272e1af61d6a3ce2656/custom.css#L19

**Comment by RoseTheFlower** [comment]
Yeah, we're talking about the same thing. Just see the instructions in the file I linked. Basically you'd copy the linked line to be inside the curly brackets at the top of the file.

**Comment by linguaccia22** [comment]
excuse me and my first time installing in theme how do I modify that file? where is it ?

**Comment by linguaccia22** [comment]
In the folder you indicated I see these files
![Immagine 2024-05-30 200246](https://github.com/RoseTheFlower/MetroSteam/assets/95597809/cedb905a-bbfe-4bf6-8607-2eca978b825f)

and one of these?

**Comment by RoseTheFlower** [comment]
If it's not in the folder, you could just download it at the page I linked, then modify it.

**Comment by linguaccia22** [comment]
I downloaded the custom.css file and placed it in the folder
"C:\Program Files (x86)\Steam\steamui\skins\MetroSteam-master"
I opened the custom.css file with WordPad
but honestly I don't understand now what I need to change.

I'm sorry if I don't immediately understand why I'm using Google Translate to communicate with you.

**Comment by linguaccia22** [comment]
Perfect it worked.
Thanks so much for the support :)
