### ISSUE TITLE
Background art is currently broken.

### ISSUE THREAD

**Issue by agedplato** [RoseTheFlower/MetroSteam#38]
![image](https://github.com/user-attachments/assets/acc1b4b8-3163-492e-9f77-d507e0a321f2)
![image](https://github.com/user-attachments/assets/81d7057a-d4ce-4de3-801d-07ce0539e5d8)
As seen above background art are cutoff just above the play button.

on Millennium Ver 2.7.2

**Comment by RoseTheFlower** [comment]
![image](https://github.com/user-attachments/assets/3e7dbf60-5516-4201-8650-764da9b34f61)
Not sure how to reproduce.

**Comment by RoseTheFlower** [comment]
Though if the issue concerns the beta, see #37.

**Comment by agedplato** [comment]
interesting, I'll have to do some more looking around to see if i can find a reason for why my art is broken.
good to know its not a problem for everyone.

**Comment by agedplato** [comment]
After further investigation i have realized that i had turned on the steam family beta without realizing.
marking as closed due to #37.
