### ISSUE TITLE
Can't add non-steam games

### ISSUE THREAD

**Issue by Snakevenoum** [RoseTheFlower/MetroSteam#39]
Usually, you would be able to add non-steam games in the bottom left of the standard steam UI. I cannot seem to find where to add non-steam games if it is an available feature.

**Comment by RoseTheFlower** [comment]
Steam logo -> Games. I tried to follow the original design of Metro for Steam while also getting rid of any cases of duplicate buttons, which Valve love so much.

**Comment by Snakevenoum** [comment]
Oh my fault for not looking properly, sorry to disturb you, I appreciate
your work.

**Comment by Snakevenoum** [comment]
![Screenshot_13](https://github.com/user-attachments/assets/c364cc58-d6d4-4ffb-beeb-fcf3a74cdac9)

Can't find the games section

**Comment by RoseTheFlower** [comment]
![image](https://github.com/user-attachments/assets/8c020de5-a40b-4a06-bf3b-3dd99787c210)

**Comment by Snakevenoum** [comment]
wow. IM blind
