### ISSUE TITLE
Game banners not showing, is this on purpose or a glitch? I am using millennium for steam

### ISSUE THREAD

**Issue by ChiefPartyPat** [RoseTheFlower/MetroSteam#40]
![Screenshot 2024-09-03 192201](https://github.com/user-attachments/assets/553e0cf5-73da-4610-b6e1-436e8bbef33d)

**Comment by RoseTheFlower** [comment]
Not sure why. They are in place on my end. Is this the stable or the beta version of Steam? Have you made any changes to the css files? Does the issue occur with any other skin or without any skin?

**Comment by ChiefPartyPat** [comment]
I just disabled steam future updates and they came back. thank you!
