### ISSUE TITLE
Dropdown Menu Items Unskinned

### ISSUE THREAD

**Issue by Sekenx** [RoseTheFlower/MetroSteam#43]
Hello!

It seems as of recently (last week or 2 I think) that these are no longer skinned

Thanks in advance

![image](https://github.com/user-attachments/assets/b84ba07b-ba3f-4256-9083-d937c1ec077c)

**Comment by RoseTheFlower** [comment]
They are skinned for me. Using the latest stable version of Steam with my latest skin version.

**Comment by Sekenx** [comment]
Ah yes you're right, I thought I had the latest but was a release behind, sorry :D
